import { useEffect, useState } from 'react';
import AutomationChat from './AutomationChat';
import SkillsPanel from './SkillsPanel';
import LiveScreenShare from './LiveScreenShare';
const API = 'http://127.0.0.1:4387';

export default function AutomationPanel({ onBack }) {
  const [task, setTask] = useState(''); const [chatNotice, setChatNotice] = useState(''); const [editingId, setEditingId] = useState(null); const [runningId, setRunningId] = useState(null); const [picker, setPicker] = useState(null); const [demoMode, setDemoMode] = useState(false); const [items, setItems] = useState([]); const [selected, setSelected] = useState(null); const [busy, setBusy] = useState(false); const [status, setStatus] = useState('Create a reusable browser automation.'); const [deleteItem, setDeleteItem] = useState(null); const [showSkills, setShowSkills] = useState(false); const [liveShare, setLiveShare] = useState(false); const [liveFrame, setLiveFrame] = useState(null);
  const refresh = async () => { try { const r=await fetch(`${API}/api/automations`); if(r.ok) setItems(await r.json()); } catch { setStatus('Automation library is temporarily unavailable.'); } };
  useEffect(() => { refresh(); fetch(`${API}/api/automations/config`).then((r)=>r.json()).then((d)=>setDemoMode(!d.hasApiKey)).catch(()=>setDemoMode(true)); }, []);
  async function create() { if(!task.trim()||busy)return; const editing=Boolean(editingId); setBusy(true); setStatus(editing?'Updating automation plan...':'AI is designing a reusable plan...'); try { const endpoint=editing ? API+'/api/automations/'+editingId : API+'/api/automations'; const r=await fetch(endpoint,{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task})}); const d=await r.json(); if(!r.ok)throw Error(d.error); if(editing){setItems((v)=>v.map((item)=>item.id===d.id?d:item));}else{setItems((v)=>[d,...v]);} setSelected(d); setEditingId(null); setTask(''); setStatus(editing?'Automation updated.':'Saved. Review it, then press Play.'); } catch(e){setStatus(e.message);} finally{setBusy(false);} }
  async function play(id) { if(busy)return;setBusy(true);setRunningId(id);setStatus('AI agent is working in the visible browser...');try{const r=await fetch(`${API}/api/automations/${id}/run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resume:items.find((item)=>item.id===id)?.status==='needs_human'})});const d=await r.json();if(!r.ok)throw Error(d.error);setSelected(d.automation);setItems((v)=>v.map((item)=>item.id===d.automation.id?d.automation:item));if(d.automation.status==='blocked'||d.automation.status==='needs_human'||d.automation.status==='failed')setChatNotice(d.automation.runs?.[0]?.logs?.at(-1)?.label || 'Automation stopped because the page requires human verification.');await refresh();setStatus(d.automation.status==='blocked'||d.automation.status==='needs_human'?'Human verification required. Solve it in the browser, then press Resume.':(d.automation.status==='failed'?'Automatic recovery failed. See Automation chat.':(d.ok?'Automation completed.':'Automation stopped safely.')));}catch(e){setChatNotice('Automation error: '+e.message);setStatus(e.message);}finally{setBusy(false);setRunningId(null);}}
  async function stopRunning(){ if(!runningId)return; await fetch(`${API}/api/automations/stop`,{method:'POST'}); setRunningId(null); setBusy(false); setStatus('Automation stopped.'); await refresh(); }
  function startLiveObserve(){ window.companion.setCaptureProtection(true); setLiveShare(true); setStatus('Live observation started. Ask the AI about the current browser screen.'); }
  function stopLiveObserve(){ window.companion.setCaptureProtection(false); setLiveShare(false); setLiveFrame(null); setStatus('Live observation stopped.'); }
  async function remove(){if(!deleteItem)return;await fetch(`${API}/api/automations/${deleteItem.id}`,{method:'DELETE'});if(selected?.id===deleteItem.id)setSelected(null);setItems((v)=>v.filter((x)=>x.id!==deleteItem.id));setDeleteItem(null);}
  const active=selected || items[0];
  return <div className="automation-panel">
    <header><div><label>PHASE TWO</label><h1>Automation library</h1><p>AI plans, observes, and chooses the next safe browser action.</p></div><span className={demoMode ? "demo-badge" : "good"}>{demoMode ? "Demo mode" : "AI configured"}</span><button onClick={()=>setShowSkills(true)}>Skills</button><button onClick={onBack}>Back to chat</button></header>
    {runningId&&<div className="automation-running"><span className="running-dot"></span><strong>Running: {items.find((item)=>item.id===runningId)?.title || 'Automation'}</strong><small>AI agent is working in the visible browser...</small><button onClick={stopRunning}>Stop automation</button></div>}<div className="automation-observe-toolbar"><button onClick={liveShare?stopLiveObserve:startLiveObserve}>{liveShare?"Stop AI observe":"AI observe screen"}</button><small>{liveShare?"Live frame stays local until you use it in automation chat.":"Use live screen observation when the page is visually unclear."}</small></div>{liveShare&&<div className="automation-live-observe"><LiveScreenShare onFrame={setLiveFrame} onClose={stopLiveObserve} />{liveFrame&&<img src={liveFrame} alt="Current live browser frame" />}</div>}{liveShare&&!selected&&<AutomationChat automationId="live-observe" task="Live screen observation" notice="Live observation is active. Ask about the current screen." screenImage={liveFrame} />}<div className="automation-layout"><div className="automation-library"><button className="new-automation" onClick={() => {setSelected(null);setEditingId(null);setTask('');}}>+ New automation</button><strong>Saved automations</strong>{items.length===0&&<small>No saved automations yet.</small>}{items.map((item)=><div className={active?.id===item.id?'automation-row selected':'automation-row'} key={item.id}><button onClick={()=>setSelected(item)}>{item.title}<small>{item.status}</small></button><button className="play" onClick={()=>play(item.id)} disabled={busy} aria-label={`Play ${item.title}`}>▶</button><button className="edit-automation" onClick={()=>{setSelected(null);setEditingId(item.id);setTask(item.task || '');setStatus('Edit the task, then save your changes.');}} aria-label="Edit automation">Edit</button><button className="delete-session" onClick={()=>setDeleteItem(item)} aria-label={`Delete ${item.title}`}>x</button></div>)}</div>
      <div className="automation-workspace">{!selected ? <div className="automation-card"><label>{editingId ? 'Edit automation task' : 'What should the browser do?'}</label><textarea value={task} onChange={(e)=>setTask(e.target.value)} placeholder="Example: Find three React UI libraries on GitHub and summarize them" disabled={busy}/>{demoMode && <p className="demo-note">Demo mode: add an OpenAI API key to create AI plans and run multi-step browser automation.</p>}<div className="automation-actions"><small>{status}</small><button className="send" onClick={create} disabled={!task.trim()||busy}>{editingId ? 'Save changes' : 'Create automation'}</button></div></div> : <><div className="automation-card"><div className="automation-title"><div><h2>{selected.title}</h2><p>{selected.summary}</p></div><span className={`automation-status ${selected.status}`}>{selected.status}</span></div><h3>AI plan</h3><ol className="plan-list">{selected.draftSteps.map((step,index)=><li key={index}>{step}</li>)}</ol>{selected.result&&<div className="automation-result"><h3>Result found</h3><p>{selected.result}</p></div>}<div className="automation-actions"><small>{status}</small><span><button onClick={()=>setSelected(null)} disabled={busy}>New automation</button><button className="send" onClick={()=>play(selected.id)} disabled={busy}>▶ Play</button></span></div></div><AutomationChat automationId={selected.id} task={selected.task} notice={chatNotice} screenImage={liveFrame} /></>}</div></div>
    {showSkills&&<div className="modal-backdrop"><div className="skills-modal"><SkillsPanel onClose={()=>setShowSkills(false)} /></div></div>}
    {deleteItem&&<div className="modal-backdrop"><div className="delete-modal"><div className="modal-icon">!</div><div><h2>Delete automation?</h2><p>“{deleteItem.title}” and its run history will be removed.</p></div><div className="modal-actions"><button onClick={()=>setDeleteItem(null)}>Cancel</button><button className="danger" onClick={remove}>Delete</button></div></div></div>}
  </div>;
}