import { useEffect, useState } from 'react';
const API='http://127.0.0.1:4387';
export default function SkillsPanel({ onClose }) {
  const [items,setItems]=useState([]); const [title,setTitle]=useState(''); const [instructions,setInstructions]=useState(''); const [status,setStatus]=useState('Save reusable instructions the AI can use in automation.');
  async function refresh(){const r=await fetch(API+'/api/skills');const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error || ('Skills API returned ' + r.status + '. Restart the app.'));setItems(Array.isArray(d)?d:[]);}
  useEffect(()=>{refresh().catch((error)=>setStatus(error.message||'Skills are temporarily unavailable.'));},[]);
  async function save(){if(!title.trim()||!instructions.trim()){setStatus('Enter both a skill title and instructions.');return;}setStatus('Saving skill...');try{const r=await fetch(API+'/api/skills',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,instructions})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error || ('Save failed (' + r.status + '). Restart the app.'));setItems((v)=>[d,...v]);setTitle('');setInstructions('');setStatus('Skill saved. The AI will use it in future automation.');}catch(error){setStatus(error.message||'Could not save skill. Restart the app.');}}
  async function remove(id){await fetch(API+'/api/skills/'+id,{method:'DELETE'});setItems((v)=>v.filter((item)=>item.id!==id));}
  return <div className="skills-panel"><div className="skills-heading"><div><label>AI SKILLS</label><h2>Reusable automation skills</h2><p>The AI reads these instructions before choosing browser actions.</p></div><button onClick={onClose}>Back to automation</button></div><div className="skills-grid"><div className="automation-card"><h3>Teach a skill</h3><input value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Example: Search job listings" /><textarea value={instructions} onChange={(e)=>setInstructions(e.target.value)} placeholder="Example: Use the search box, submit the query, open one public result, and extract title, company, location, and URL." /><div className="automation-actions"><small>{status}</small><button className="send" onClick={save} disabled={!title.trim()||!instructions.trim()}>Save skill</button></div></div><div className="automation-card"><h3>Saved skills</h3>{!items.length&&<small>No skills saved yet.</small>}{items.map((item)=><div className="skill-row" key={item.id}><div><strong>{item.title}</strong><p>{item.instructions}</p></div><button className="delete-session" onClick={()=>remove(item.id)} aria-label={'Delete '+item.title}>x</button></div>)}</div></div></div>;
}